baseURL = "https://taurus-silver-17.github.io/"
languageCode = "en-us"
title = "Arnaud Jullemier Blog"
theme = "PaperMod"

[params]
  author = "Arnaud Jullemier"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 10

[[menu.main]]
  identifier = "blog"
  name = "Article"
  url = "/posts/"
  weight = 20

[[menu.main]]
  identifier = "cv"
  name = "CV"
  url = "/files/cv.pdf"
  weight = 30

